title: Iddo Software
subtitle: A Machine Learning Company
description: >- # this means to ignore newlines until "baseurl:"
  NaNaNaNaNa BTAMAN.

url: "https://ghivi.ro" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Portofolio
      url: /blog
#    - text: Shop
#      url : /shop/
    - text: About Us
      url: /about/
    - text: Contact Us
      url : /contact/
#    - text: Styleguide
#      url: /styleguide/
    

# Edit these details 

author_logo: icon_big.png
author: IDDO
author_bio: We are a small company focused on computer vision and machine learning projects.
author_email: "info@iddo.ro"
author_location: Brasov, Romania
author_website_url:

author_work_experiences: 
            - company_name: Google
              company_logo: google.png
              company_url: https://google.com
              designation: Software Engineer
              description: Worked on various Google Products
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Azure Developer
              description: Worked on various Azure Cloud Products
              visibility: true

author_education_details:
              - college_logo: mit.png
                college_name: MIT
                college_url: https://mit.org
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: programmingebooks.png
                project_title: Programming Ebooks
                project_description: A Platform to easily find and read programming books
                project_url: https://programmingebooks.com
                visibility: true

what_we_do_details:
              - service_thumbnail: AI_consultancy.jpg
                service_title: Consultancy
                service_description: We help define your problem in the AI field. Analyze SOTA standards and estimate the costs (in required resources/ time/ additional expertise).
                visibility: true
              - service_thumbnail: AI_dev.png
                service_title: Development
                service_description: Full stack ML. From analyzing existing algorithms to deployment on your favorite platform. We have out own trining hardware, so we can be fully contained if needed.
                visibility: true
              - service_thumbnail: AI_reseach.jpg
                service_title: Research
                service_description: Redefine the unknown.
                visibility: true

how_we_do_details:
              - step_title: Initial commit
                step_description: Understanding the business goals / processes.
                visibility: true
              - step_title: AI aproach
                step_description: Identifying stages in the pipeline which might benefit from using a CV/ML approach.
                visibility: true
              - step_title: SOTA
                step_description: Researching the state of the art in the relevant field.
                visibility: true
              - step_title: What about the costs?
                step_description: Estimate the relative cost, time to market and expected performance of alternatives we find (or think of).
                visibility: true
              - step_title: Time to work
                step_description: Solution design, implementation, testing, deployment and maintenance.
                visibility: true
# social links
twitter_username:
github_username:  iddosoftware
facebook_username:
linkedin_username: iddo-software
behance_username:
instagram_username:
medium_username:
telegram_username:
dribbble_username:
flickr_username:

#for comments using disqus
disqus_shortname: iddo

# wakatime username (coding activity)
wakatime_username:

# formspree (contact form)
formspree_email: info@iddo.ro

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: false
show_author_education_details: false
show_author_project_details: false
show_what_we_do: true
show_how_we_do: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search 
#algolia:
#  application_id: D9WA1YKTRQ
#  index_name: blog_posts # You can replace that with whatever name you want
#  files_to_exclude: []
#  nodes_to_index: 'article'
#  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - products

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/